
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb
    username: root
    password: lihaolong0226
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    # 163??????smtp.163.com???????
    host: smtp.163.com
    # ????163??
    username: 17537709956@163.com
    # ????????smtp/pop3?????????????????????
    password: HRFGHDEBREOTYKLS
server:
  port: 8080

